name: Deploy Bicep Lab to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      vmSize:
        description: 'VM Size'
        required: false
        default: 'Standard_B2s'
        type: choice
        options:
          - 'Standard_B1s'
          - 'Standard_B2s'
          - 'Standard_B4ms'
      enablePublicIP:
        description: 'Enable Public IP'
        required: false
        default: true
        type: boolean

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          managed-identity-client-id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Create Resource Group
        run: |
          az group create \
            --name thornetlab-rg \
            --location "East US" \
            --tags project=thornetlab environment=lab

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: thornetlab-rg
          template: ./bicep/main.bicep
          parameters: |
            location="East US"
            vmName="thornetlab-ubuntu"
            adminUsername="azureuser"
            sshPublicKey="${{ secrets.SSH_PUBLIC_KEY }}"
            vmSize="${{ github.event.inputs.vmSize || 'Standard_B2s' }}"
            enablePublicIP=${{ github.event.inputs.enablePublicIP || true }}

      - name: Display deployment outputs
        run: |
          echo "Deployment completed successfully!"
          echo "Check the Azure portal for deployment outputs including SSH connection details."
