name: Deploy Bicep Lab to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          managed-identity-client-id: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Deploy Bicep file
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: thornetlab-rg
          template: ./bicep/main.bicep
          parameters: @./bicep/parameters/lab.parameters.json
